set(_CATKIN_CURRENT_PACKAGE "robot_serving")
set(robot_serving_VERSION "1.0.0")
set(robot_serving_MAINTAINER "miguel <miguel.afonso.faria@gmail.com>")
set(robot_serving_PACKAGE_FORMAT "1")
set(robot_serving_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs" "geometry_msgs" "image_transport" "sensor_msgs" "cv_bridge")
set(robot_serving_BUILD_EXPORT_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs" "geometry_msgs" "image_transport" "sensor_msgs" "cv_bridge")
set(robot_serving_BUILDTOOL_DEPENDS "catkin")
set(robot_serving_BUILDTOOL_EXPORT_DEPENDS )
set(robot_serving_EXEC_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs" "geometry_msgs" "image_transport" "sensor_msgs" "cv_bridge")
set(robot_serving_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs" "geometry_msgs" "image_transport" "sensor_msgs" "cv_bridge")
set(robot_serving_TEST_DEPENDS )
set(robot_serving_DOC_DEPENDS )
set(robot_serving_DEPRECATED "")