# Request fields
float64 	x_pos			# cup x position
float64 	y_pos			# cup y position
float64 	z_pos			# cup z position
---
# Service response
PMPTraj 	robot_trajectory 	# vector with the sequence of joint angles to perform the given movement