// Generated by gencpp from file robot_serving/Movement.msg
// DO NOT EDIT!


#ifndef ROBOT_SERVING_MESSAGE_MOVEMENT_H
#define ROBOT_SERVING_MESSAGE_MOVEMENT_H

#include <ros/service_traits.h>


#include <robot_serving/MovementRequest.h>
#include <robot_serving/MovementResponse.h>


namespace robot_serving
{

struct Movement
{

typedef MovementRequest Request;
typedef MovementResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Movement
} // namespace robot_serving


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_serving::Movement > {
  static const char* value()
  {
    return "603e8705159b0ff81a425568466a053a";
  }

  static const char* value(const ::robot_serving::Movement&) { return value(); }
};

template<>
struct DataType< ::robot_serving::Movement > {
  static const char* value()
  {
    return "robot_serving/Movement";
  }

  static const char* value(const ::robot_serving::Movement&) { return value(); }
};


// service_traits::MD5Sum< ::robot_serving::MovementRequest> should match 
// service_traits::MD5Sum< ::robot_serving::Movement > 
template<>
struct MD5Sum< ::robot_serving::MovementRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_serving::Movement >::value();
  }
  static const char* value(const ::robot_serving::MovementRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_serving::MovementRequest> should match 
// service_traits::DataType< ::robot_serving::Movement > 
template<>
struct DataType< ::robot_serving::MovementRequest>
{
  static const char* value()
  {
    return DataType< ::robot_serving::Movement >::value();
  }
  static const char* value(const ::robot_serving::MovementRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_serving::MovementResponse> should match 
// service_traits::MD5Sum< ::robot_serving::Movement > 
template<>
struct MD5Sum< ::robot_serving::MovementResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_serving::Movement >::value();
  }
  static const char* value(const ::robot_serving::MovementResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_serving::MovementResponse> should match 
// service_traits::DataType< ::robot_serving::Movement > 
template<>
struct DataType< ::robot_serving::MovementResponse>
{
  static const char* value()
  {
    return DataType< ::robot_serving::Movement >::value();
  }
  static const char* value(const ::robot_serving::MovementResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_SERVING_MESSAGE_MOVEMENT_H
