// Generated by gencpp from file robot_serving/MovementRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_SERVING_MESSAGE_MOVEMENTREQUEST_H
#define ROBOT_SERVING_MESSAGE_MOVEMENTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_serving
{
template <class ContainerAllocator>
struct MovementRequest_
{
  typedef MovementRequest_<ContainerAllocator> Type;

  MovementRequest_()
    : x_pos(0.0)
    , y_pos(0.0)
    , z_pos(0.0)  {
    }
  MovementRequest_(const ContainerAllocator& _alloc)
    : x_pos(0.0)
    , y_pos(0.0)
    , z_pos(0.0)  {
  (void)_alloc;
    }



   typedef double _x_pos_type;
  _x_pos_type x_pos;

   typedef double _y_pos_type;
  _y_pos_type y_pos;

   typedef double _z_pos_type;
  _z_pos_type z_pos;




  typedef boost::shared_ptr< ::robot_serving::MovementRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_serving::MovementRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MovementRequest_

typedef ::robot_serving::MovementRequest_<std::allocator<void> > MovementRequest;

typedef boost::shared_ptr< ::robot_serving::MovementRequest > MovementRequestPtr;
typedef boost::shared_ptr< ::robot_serving::MovementRequest const> MovementRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_serving::MovementRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_serving::MovementRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_serving

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'robot_serving': ['/home/miguel/catkin_ws/src/robot_serving/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_serving::MovementRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_serving::MovementRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_serving::MovementRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_serving::MovementRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_serving::MovementRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_serving::MovementRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_serving::MovementRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7c86352f4ebc779b97e82ba1774c24ad";
  }

  static const char* value(const ::robot_serving::MovementRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7c86352f4ebc779bULL;
  static const uint64_t static_value2 = 0x97e82ba1774c24adULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_serving::MovementRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_serving/MovementRequest";
  }

  static const char* value(const ::robot_serving::MovementRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_serving::MovementRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
float64 	x_pos\n\
float64 	y_pos\n\
float64 	z_pos\n\
";
  }

  static const char* value(const ::robot_serving::MovementRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_serving::MovementRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_pos);
      stream.next(m.y_pos);
      stream.next(m.z_pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MovementRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_serving::MovementRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_serving::MovementRequest_<ContainerAllocator>& v)
  {
    s << indent << "x_pos: ";
    Printer<double>::stream(s, indent + "  ", v.x_pos);
    s << indent << "y_pos: ";
    Printer<double>::stream(s, indent + "  ", v.y_pos);
    s << indent << "z_pos: ";
    Printer<double>::stream(s, indent + "  ", v.z_pos);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_SERVING_MESSAGE_MOVEMENTREQUEST_H
