// Generated by gencpp from file robot_serving/RobotMovementFeedbackRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_SERVING_MESSAGE_ROBOTMOVEMENTFEEDBACKREQUEST_H
#define ROBOT_SERVING_MESSAGE_ROBOTMOVEMENTFEEDBACKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_serving
{
template <class ContainerAllocator>
struct RobotMovementFeedbackRequest_
{
  typedef RobotMovementFeedbackRequest_<ContainerAllocator> Type;

  RobotMovementFeedbackRequest_()
    : limb()  {
    }
  RobotMovementFeedbackRequest_(const ContainerAllocator& _alloc)
    : limb(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _limb_type;
  _limb_type limb;




  typedef boost::shared_ptr< ::robot_serving::RobotMovementFeedbackRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_serving::RobotMovementFeedbackRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RobotMovementFeedbackRequest_

typedef ::robot_serving::RobotMovementFeedbackRequest_<std::allocator<void> > RobotMovementFeedbackRequest;

typedef boost::shared_ptr< ::robot_serving::RobotMovementFeedbackRequest > RobotMovementFeedbackRequestPtr;
typedef boost::shared_ptr< ::robot_serving::RobotMovementFeedbackRequest const> RobotMovementFeedbackRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_serving::RobotMovementFeedbackRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_serving::RobotMovementFeedbackRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_serving

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'robot_serving': ['/home/miguel/catkin_ws/src/robot_serving/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_serving::RobotMovementFeedbackRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_serving::RobotMovementFeedbackRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_serving::RobotMovementFeedbackRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_serving::RobotMovementFeedbackRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_serving::RobotMovementFeedbackRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_serving::RobotMovementFeedbackRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_serving::RobotMovementFeedbackRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "19c8cc0605dd732f7b85a926ecaf03a2";
  }

  static const char* value(const ::robot_serving::RobotMovementFeedbackRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x19c8cc0605dd732fULL;
  static const uint64_t static_value2 = 0x7b85a926ecaf03a2ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_serving::RobotMovementFeedbackRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_serving/RobotMovementFeedbackRequest";
  }

  static const char* value(const ::robot_serving::RobotMovementFeedbackRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_serving::RobotMovementFeedbackRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
string 	limb\n\
";
  }

  static const char* value(const ::robot_serving::RobotMovementFeedbackRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_serving::RobotMovementFeedbackRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.limb);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct RobotMovementFeedbackRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_serving::RobotMovementFeedbackRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_serving::RobotMovementFeedbackRequest_<ContainerAllocator>& v)
  {
    s << indent << "limb: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.limb);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_SERVING_MESSAGE_ROBOTMOVEMENTFEEDBACKREQUEST_H
