// Generated by gencpp from file robot_serving/RobotMovementSendTrajectory.msg
// DO NOT EDIT!


#ifndef ROBOT_SERVING_MESSAGE_ROBOTMOVEMENTSENDTRAJECTORY_H
#define ROBOT_SERVING_MESSAGE_ROBOTMOVEMENTSENDTRAJECTORY_H

#include <ros/service_traits.h>


#include <robot_serving/RobotMovementSendTrajectoryRequest.h>
#include <robot_serving/RobotMovementSendTrajectoryResponse.h>


namespace robot_serving
{

struct RobotMovementSendTrajectory
{

typedef RobotMovementSendTrajectoryRequest Request;
typedef RobotMovementSendTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotMovementSendTrajectory
} // namespace robot_serving


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_serving::RobotMovementSendTrajectory > {
  static const char* value()
  {
    return "49578c603e30c444612b55184f196db2";
  }

  static const char* value(const ::robot_serving::RobotMovementSendTrajectory&) { return value(); }
};

template<>
struct DataType< ::robot_serving::RobotMovementSendTrajectory > {
  static const char* value()
  {
    return "robot_serving/RobotMovementSendTrajectory";
  }

  static const char* value(const ::robot_serving::RobotMovementSendTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::robot_serving::RobotMovementSendTrajectoryRequest> should match 
// service_traits::MD5Sum< ::robot_serving::RobotMovementSendTrajectory > 
template<>
struct MD5Sum< ::robot_serving::RobotMovementSendTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_serving::RobotMovementSendTrajectory >::value();
  }
  static const char* value(const ::robot_serving::RobotMovementSendTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_serving::RobotMovementSendTrajectoryRequest> should match 
// service_traits::DataType< ::robot_serving::RobotMovementSendTrajectory > 
template<>
struct DataType< ::robot_serving::RobotMovementSendTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::robot_serving::RobotMovementSendTrajectory >::value();
  }
  static const char* value(const ::robot_serving::RobotMovementSendTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_serving::RobotMovementSendTrajectoryResponse> should match 
// service_traits::MD5Sum< ::robot_serving::RobotMovementSendTrajectory > 
template<>
struct MD5Sum< ::robot_serving::RobotMovementSendTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_serving::RobotMovementSendTrajectory >::value();
  }
  static const char* value(const ::robot_serving::RobotMovementSendTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_serving::RobotMovementSendTrajectoryResponse> should match 
// service_traits::DataType< ::robot_serving::RobotMovementSendTrajectory > 
template<>
struct DataType< ::robot_serving::RobotMovementSendTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::robot_serving::RobotMovementSendTrajectory >::value();
  }
  static const char* value(const ::robot_serving::RobotMovementSendTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_SERVING_MESSAGE_ROBOTMOVEMENTSENDTRAJECTORY_H
