// Generated by gencpp from file robot_serving/RobotMovementFeedbackResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_SERVING_MESSAGE_ROBOTMOVEMENTFEEDBACKRESPONSE_H
#define ROBOT_SERVING_MESSAGE_ROBOTMOVEMENTFEEDBACKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_serving
{
template <class ContainerAllocator>
struct RobotMovementFeedbackResponse_
{
  typedef RobotMovementFeedbackResponse_<ContainerAllocator> Type;

  RobotMovementFeedbackResponse_()
    : feedback(0)  {
    }
  RobotMovementFeedbackResponse_(const ContainerAllocator& _alloc)
    : feedback(0)  {
  (void)_alloc;
    }



   typedef int32_t _feedback_type;
  _feedback_type feedback;




  typedef boost::shared_ptr< ::robot_serving::RobotMovementFeedbackResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_serving::RobotMovementFeedbackResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RobotMovementFeedbackResponse_

typedef ::robot_serving::RobotMovementFeedbackResponse_<std::allocator<void> > RobotMovementFeedbackResponse;

typedef boost::shared_ptr< ::robot_serving::RobotMovementFeedbackResponse > RobotMovementFeedbackResponsePtr;
typedef boost::shared_ptr< ::robot_serving::RobotMovementFeedbackResponse const> RobotMovementFeedbackResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_serving::RobotMovementFeedbackResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_serving::RobotMovementFeedbackResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_serving

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'robot_serving': ['/home/miguel/catkin_ws/src/robot_serving/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_serving::RobotMovementFeedbackResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_serving::RobotMovementFeedbackResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_serving::RobotMovementFeedbackResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_serving::RobotMovementFeedbackResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_serving::RobotMovementFeedbackResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_serving::RobotMovementFeedbackResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_serving::RobotMovementFeedbackResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49ceb5b32ea3af22073ede4a0328249e";
  }

  static const char* value(const ::robot_serving::RobotMovementFeedbackResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49ceb5b32ea3af22ULL;
  static const uint64_t static_value2 = 0x073ede4a0328249eULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_serving::RobotMovementFeedbackResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_serving/RobotMovementFeedbackResponse";
  }

  static const char* value(const ::robot_serving::RobotMovementFeedbackResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_serving::RobotMovementFeedbackResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
int32 	feedback\n\
";
  }

  static const char* value(const ::robot_serving::RobotMovementFeedbackResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_serving::RobotMovementFeedbackResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct RobotMovementFeedbackResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_serving::RobotMovementFeedbackResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_serving::RobotMovementFeedbackResponse_<ContainerAllocator>& v)
  {
    s << indent << "feedback: ";
    Printer<int32_t>::stream(s, indent + "  ", v.feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_SERVING_MESSAGE_ROBOTMOVEMENTFEEDBACKRESPONSE_H
