// Generated by gencpp from file robot_serving/RobotMovementCancelTrajectory.msg
// DO NOT EDIT!


#ifndef ROBOT_SERVING_MESSAGE_ROBOTMOVEMENTCANCELTRAJECTORY_H
#define ROBOT_SERVING_MESSAGE_ROBOTMOVEMENTCANCELTRAJECTORY_H

#include <ros/service_traits.h>


#include <robot_serving/RobotMovementCancelTrajectoryRequest.h>
#include <robot_serving/RobotMovementCancelTrajectoryResponse.h>


namespace robot_serving
{

struct RobotMovementCancelTrajectory
{

typedef RobotMovementCancelTrajectoryRequest Request;
typedef RobotMovementCancelTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotMovementCancelTrajectory
} // namespace robot_serving


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_serving::RobotMovementCancelTrajectory > {
  static const char* value()
  {
    return "ad679c59351570bb04b061c3d5ba035b";
  }

  static const char* value(const ::robot_serving::RobotMovementCancelTrajectory&) { return value(); }
};

template<>
struct DataType< ::robot_serving::RobotMovementCancelTrajectory > {
  static const char* value()
  {
    return "robot_serving/RobotMovementCancelTrajectory";
  }

  static const char* value(const ::robot_serving::RobotMovementCancelTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::robot_serving::RobotMovementCancelTrajectoryRequest> should match 
// service_traits::MD5Sum< ::robot_serving::RobotMovementCancelTrajectory > 
template<>
struct MD5Sum< ::robot_serving::RobotMovementCancelTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_serving::RobotMovementCancelTrajectory >::value();
  }
  static const char* value(const ::robot_serving::RobotMovementCancelTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_serving::RobotMovementCancelTrajectoryRequest> should match 
// service_traits::DataType< ::robot_serving::RobotMovementCancelTrajectory > 
template<>
struct DataType< ::robot_serving::RobotMovementCancelTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::robot_serving::RobotMovementCancelTrajectory >::value();
  }
  static const char* value(const ::robot_serving::RobotMovementCancelTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_serving::RobotMovementCancelTrajectoryResponse> should match 
// service_traits::MD5Sum< ::robot_serving::RobotMovementCancelTrajectory > 
template<>
struct MD5Sum< ::robot_serving::RobotMovementCancelTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_serving::RobotMovementCancelTrajectory >::value();
  }
  static const char* value(const ::robot_serving::RobotMovementCancelTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_serving::RobotMovementCancelTrajectoryResponse> should match 
// service_traits::DataType< ::robot_serving::RobotMovementCancelTrajectory > 
template<>
struct DataType< ::robot_serving::RobotMovementCancelTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::robot_serving::RobotMovementCancelTrajectory >::value();
  }
  static const char* value(const ::robot_serving::RobotMovementCancelTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_SERVING_MESSAGE_ROBOTMOVEMENTCANCELTRAJECTORY_H
