// Generated by gencpp from file robot_serving/RobotMovementFeedback.msg
// DO NOT EDIT!


#ifndef ROBOT_SERVING_MESSAGE_ROBOTMOVEMENTFEEDBACK_H
#define ROBOT_SERVING_MESSAGE_ROBOTMOVEMENTFEEDBACK_H

#include <ros/service_traits.h>


#include <robot_serving/RobotMovementFeedbackRequest.h>
#include <robot_serving/RobotMovementFeedbackResponse.h>


namespace robot_serving
{

struct RobotMovementFeedback
{

typedef RobotMovementFeedbackRequest Request;
typedef RobotMovementFeedbackResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotMovementFeedback
} // namespace robot_serving


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_serving::RobotMovementFeedback > {
  static const char* value()
  {
    return "42c90eeae941df68ef24a656cdcd8c94";
  }

  static const char* value(const ::robot_serving::RobotMovementFeedback&) { return value(); }
};

template<>
struct DataType< ::robot_serving::RobotMovementFeedback > {
  static const char* value()
  {
    return "robot_serving/RobotMovementFeedback";
  }

  static const char* value(const ::robot_serving::RobotMovementFeedback&) { return value(); }
};


// service_traits::MD5Sum< ::robot_serving::RobotMovementFeedbackRequest> should match 
// service_traits::MD5Sum< ::robot_serving::RobotMovementFeedback > 
template<>
struct MD5Sum< ::robot_serving::RobotMovementFeedbackRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_serving::RobotMovementFeedback >::value();
  }
  static const char* value(const ::robot_serving::RobotMovementFeedbackRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_serving::RobotMovementFeedbackRequest> should match 
// service_traits::DataType< ::robot_serving::RobotMovementFeedback > 
template<>
struct DataType< ::robot_serving::RobotMovementFeedbackRequest>
{
  static const char* value()
  {
    return DataType< ::robot_serving::RobotMovementFeedback >::value();
  }
  static const char* value(const ::robot_serving::RobotMovementFeedbackRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_serving::RobotMovementFeedbackResponse> should match 
// service_traits::MD5Sum< ::robot_serving::RobotMovementFeedback > 
template<>
struct MD5Sum< ::robot_serving::RobotMovementFeedbackResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_serving::RobotMovementFeedback >::value();
  }
  static const char* value(const ::robot_serving::RobotMovementFeedbackResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_serving::RobotMovementFeedbackResponse> should match 
// service_traits::DataType< ::robot_serving::RobotMovementFeedback > 
template<>
struct DataType< ::robot_serving::RobotMovementFeedbackResponse>
{
  static const char* value()
  {
    return DataType< ::robot_serving::RobotMovementFeedback >::value();
  }
  static const char* value(const ::robot_serving::RobotMovementFeedbackResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_SERVING_MESSAGE_ROBOTMOVEMENTFEEDBACK_H
