(cl:defpackage robot_serving-srv
  (:use )
  (:export
   "ROBOTMOVEMENTCANCELTRAJECTORY"
   "<ROBOTMOVEMENTCANCELTRAJECTORY-REQUEST>"
   "ROBOTMOVEMENTCANCELTRAJECTORY-REQUEST"
   "<ROBOTMOVEMENTCANCELTRAJECTORY-RESPONSE>"
   "ROBOTMOVEMENTCANCELTRAJECTORY-RESPONSE"
   "MOVEMENT"
   "<MOVEMENT-REQUEST>"
   "MOVEMENT-REQUEST"
   "<MOVEMENT-RESPONSE>"
   "MOVEMENT-RESPONSE"
   "ROBOTMOVEMENTFEEDBACK"
   "<ROBOTMOVEMENTFEEDBACK-REQUEST>"
   "ROBOTMOVEMENTFEEDBACK-REQUEST"
   "<ROBOTMOVEMENTFEEDBACK-RESPONSE>"
   "ROBOTMOVEMENTFEEDBACK-RESPONSE"
   "ROBOTMOVEMENTSENDTRAJECTORY"
   "<ROBOTMOVEMENTSENDTRAJECTORY-REQUEST>"
   "ROBOTMOVEMENTSENDTRAJECTORY-REQUEST"
   "<ROBOTMOVEMENTSENDTRAJECTORY-RESPONSE>"
   "ROBOTMOVEMENTSENDTRAJECTORY-RESPONSE"
  ))

